#!/usr/bin/env python
"""Audit likely orphan docs/skills/tools against the generated pipeline map."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools import pipeline_map

DEFAULT_OUT_DIR = ROOT / "docs" / "generated"
REF_RE = re.compile(r"(?P<path>(?:docs|skills|tools)/[A-Za-z0-9_./-]+\.(?:md|py))")


def _rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def _existing(paths: list[str]) -> set[str]:
    return {path for path in paths if (ROOT / path).is_file()}


def _read_refs(path: str) -> set[str]:
    source = ROOT / path
    if not source.is_file():
        return set()
    try:
        text = source.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        text = source.read_text(encoding="utf-8", errors="ignore")
    return {match.group("path").rstrip(").,") for match in REF_RE.finditer(text)}


def collect_direct_refs(data: dict[str, Any]) -> set[str]:
    refs: set[str] = set(data["active_docs"] + data["active_skills"] + data["core_tools"])
    for tools in data.get("support_tools", {}).values():
        refs.update(tools)
    for stage in data["stages"]:
        refs.update(stage.get("docs", []))
        refs.update(stage.get("skills", []))
        refs.update(tool.split(":", 1)[0].split(" ", 1)[0] for tool in stage.get("tools", []))
    for branch in data["branches"]:
        refs.update(branch.get("docs", []))
        refs.update(branch.get("skills", []))
    return _existing(sorted(refs))


def collect_active_refs(data: dict[str, Any]) -> set[str]:
    direct_refs = collect_direct_refs(data)
    refs: set[str] = set(direct_refs)

    # INDEX.md is a catalog. It should not promote every listed doc to active.
    frontier = [ref for ref in sorted(direct_refs) if ref != "docs/INDEX.md"]
    seen = set(frontier)
    while frontier:
        current = frontier.pop()
        for ref in _read_refs(current):
            if ref in seen or not (ROOT / ref).is_file():
                continue
            seen.add(ref)
            refs.add(ref)
            if ref.endswith(".md"):
                frontier.append(ref)
    return _existing(sorted(refs))


def build_audit() -> dict[str, Any]:
    data = pipeline_map.build_map()
    direct_active = collect_direct_refs(data)
    active = collect_active_refs(data)
    docs = {_rel(path) for path in (ROOT / "docs").rglob("*.md")}
    skills = {_rel(path) for path in (ROOT / "skills").glob("*.md")}
    tools = {_rel(path) for path in (ROOT / "tools").glob("*.py")}

    archive_docs = {path for path in docs if path.startswith("docs/archive/")}
    construction_docs = {path for path in docs if path.startswith("docs/construction-guides/")}
    generated_docs = {path for path in docs if path.startswith("docs/generated/")}
    root_docs = docs - archive_docs - construction_docs - generated_docs

    candidate_docs = sorted(root_docs - active)
    candidate_skills = sorted(skills - active)
    candidate_tools = sorted(tools - active)

    return {
        "artifact_role": "orphan_audit",
        "version": 1,
        "source_of_truth": "tools/pipeline_map.py",
        "graphify_status": "semantic_graph_not_run_missing_backend_key",
        "direct_active_count": len(direct_active),
        "active_reference_count": len(active),
        "counts": {
            "root_docs": len(root_docs),
            "construction_docs": len(construction_docs),
            "archive_docs": len(archive_docs),
            "skills": len(skills),
            "tools": len(tools),
            "candidate_docs": len(candidate_docs),
            "candidate_skills": len(candidate_skills),
            "candidate_tools": len(candidate_tools),
        },
        "candidate_docs": candidate_docs,
        "candidate_skills": candidate_skills,
        "candidate_tools": candidate_tools,
        "direct_active_refs": sorted(direct_active),
        "construction_docs": sorted(construction_docs),
        "generated_docs": sorted(generated_docs),
    }


def write_json(data: dict[str, Any], out_dir: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "orphan_audit.json"
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    return path


def write_markdown(data: dict[str, Any], out_dir: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Orphan Audit",
        "",
        "Generated by `tools/orphan_audit.py`.",
        "",
        f"- Source of truth: `{data['source_of_truth']}`",
        f"- Graphify status: `{data['graphify_status']}`",
        f"- Direct active count: {data['direct_active_count']}",
        f"- Active reference count: {data['active_reference_count']}",
        "",
        "## Counts",
        "",
    ]
    for key, value in data["counts"].items():
        lines.append(f"- `{key}`: {value}")

    def add_list(title: str, items: list[str]) -> None:
        lines.extend(["", f"## {title}", ""])
        if not items:
            lines.append("None.")
            return
        for item in items:
            lines.append(f"- `{item}`")

    add_list("Candidate Root Docs To Review", data["candidate_docs"])
    add_list("Candidate Skills To Review", data["candidate_skills"])
    add_list("Candidate Tools To Review", data["candidate_tools"])
    add_list("Construction Docs", data["construction_docs"])
    path = out_dir / "orphan_audit.md"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out-dir", default=str(DEFAULT_OUT_DIR))
    parser.add_argument("--json-only", action="store_true")
    args = parser.parse_args(argv)

    data = build_audit()
    out_dir = Path(args.out_dir)
    outputs = [write_json(data, out_dir)]
    if not args.json_only:
        outputs.append(write_markdown(data, out_dir))
    for output in outputs:
        print(_rel(output))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
